apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace:  mnp-test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        project: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80