apiVersion: octopus.io/v1alpha1
kind: MultiNetworkPolicy
metadata:
  name: test-network-policy
  namespace: mnp-test
spec:
  podSelector:
    matchLabels:
      project: test
  egress:
    allow:
      - serviceSelector:
          matchLabels:
            project: test
    ports:
      - protocol: TCP
        port: 80
        endPort: 90
      - protocol: TCP
        port: 90
        endPort: 100