apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: mnp-test
  labels:
    app: nginx
spec:
  ports:
    - name: nginx
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP