apiVersion: v1
kind: Namespace
metadata:
  name: octopus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-agent
  namespace: octopus
  labels:
    {{- include "octopus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "octopus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "octopus.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: octopus-agent
      securityContext: {}
      containers:
        - name: octopus-agent
          env:
            - name: BROKER_K8S_APISERVER
              value: {{.Values.broker.server}}
            - name: BROKER_K8S_APISERVERTOKEN
              value: {{.Values.broker.token}}
            - name: BROKER_K8S_CA
              value: {{.Values.broker.ca}}
            - name: BROKER_K8S_INSECURE
              value: "false"
          args:
            - "--clusterID={{.Values.octopus.clusterID}}"
            - "--iptables-sync-period={{.Values.octopus.iptablesSyncPeriod}}"
          image: "{{ .Values.image.repositoryAgent }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - ALL
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          resources: {}
          volumeMounts:
            - mountPath: /run/xtables.lock
              name: xtables-lock
            - mountPath: /sys
              name: host-sys
            - mountPath:  /run/openvswitch/db.sock
              name: host-run-openvswitch-db-sock
      hostNetwork: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: xtables-lock
          hostPath:
            path:  /run/xtables.lock
            type: ""
        - name: host-sys
          hostPath:
            path: /sys
            type: ""
        - name: host-run-openvswitch-db-sock
          hostPath:
            path: /run/openvswitch/db.sock
            type: ""