{{- if .Values.serviceAccounts.client.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: octopus-broker-client
  namespace: octopus
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "octopus-broker.chart" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: octopus-broker-client-token
  namespace: octopus
  annotations:
    kubernetes.io/service-account.name: octopus-broker-client
type: kubernetes.io/service-account-token
{{- end }}